name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tgcf_topicIDs
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /
